# Generated by Django 3.2 on 2023-05-23 11:26

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_placesprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=posts.models.image_post_user)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_created', to='accounts.userprofile')),
                ('likers', models.ManyToManyField(blank=True, related_name='liked', related_query_name='liked', to='accounts.UserProfile')),
            ],
        ),
    ]
