# Generated by Django 3.2 on 2023-05-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_placesprofile'),
        ('posts', '0002_commentpostuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.postuser')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', related_query_name='liked_post', to='accounts.userprofile')),
            ],
        ),
    ]
