# Generated by Django 3.2 on 2023-05-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230524_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
