# Generated by Django 3.2 on 2023-05-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comments_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepostuser',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepostuser',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='likers',
        ),
        migrations.DeleteModel(
            name='CommentPostUser',
        ),
        migrations.DeleteModel(
            name='LikePostUser',
        ),
        migrations.DeleteModel(
            name='PostUser',
        ),
    ]
