# Generated by Django 3.2 on 2023-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230527_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='interest',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
