# Generated by Django 3.2 on 2023-05-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostUser',
        ),
    ]
