# Generated by Django 3.2 on 2023-06-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='interest_community')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'interest_community',
                'verbose_name_plural': 'interest_community',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='interest',
            field=models.ManyToManyField(related_name='interests', to='community.InterestCommunity'),
        ),
    ]
