# Generated by Django 3.2 on 2023-05-20 12:11

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.image_user)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_day', models.DateField(null=True)),
                ('type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=30)),
                ('job_tite', models.CharField(max_length=15)),
                ('about_me', models.TextField(max_length=1000, null=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
