# Generated by Django 3.2 on 2023-05-26 21:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=accounts.models.image_places),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=accounts.models.image_user),
        ),
    ]
