# Generated by Django 3.2 on 2023-05-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230527_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesprofile',
            name='facebook',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='placesprofile',
            name='instagram',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
