# Generated by Django 3.2 on 2023-05-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
