# Generated by Django 3.2 on 2023-06-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_interests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='InterestUser',
        ),
    ]
