# Generated by Django 3.2 on 2023-06-21 19:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230611_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_places),
        ),
        migrations.AlterField(
            model_name='placesprofile',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='interests', to='accounts.InterestPlaces'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_user),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='interests', to='accounts.InterestUser'),
        ),
    ]
