# Generated by Django 3.2 on 2023-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230621_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestplaces',
            options={'verbose_name': 'interest_places', 'verbose_name_plural': 'interest_places'},
        ),
        migrations.AlterModelOptions(
            name='interestuser',
            options={'verbose_name': 'interest_user', 'verbose_name_plural': 'interest_user'},
        ),
        migrations.AlterField(
            model_name='interestplaces',
            name='title',
            field=models.CharField(max_length=75, verbose_name='interest_places'),
        ),
        migrations.AlterField(
            model_name='interestuser',
            name='title',
            field=models.CharField(max_length=75, verbose_name='interest_user'),
        ),
        migrations.AlterField(
            model_name='placesprofile',
            name='interest',
            field=models.ManyToManyField(related_name='interests', to='accounts.InterestPlaces'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.ManyToManyField(related_name='interests', to='accounts.InterestUser'),
        ),
    ]
